// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSA72fBSbo7q6QX7VtUL4NRi_AfV1qY0',
    appId: '1:604985196280:web:253cdcc4e4d4285023850d',
    messagingSenderId: '604985196280',
    projectId: 'e-learning-efc23',
    authDomain: 'e-learning-efc23.firebaseapp.com',
    storageBucket: 'e-learning-efc23.appspot.com',
    measurementId: 'G-5G4QN750HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX70giUrkAz0mJkYcmYChqEkI1ZrieryU',
    appId: '1:604985196280:android:2c14114a45edaf7523850d',
    messagingSenderId: '604985196280',
    projectId: 'e-learning-efc23',
    storageBucket: 'e-learning-efc23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-qiaqMycXI_HyXgsCGFxFB9XK-MXeH9I',
    appId: '1:604985196280:ios:680e7d19d95e086923850d',
    messagingSenderId: '604985196280',
    projectId: 'e-learning-efc23',
    storageBucket: 'e-learning-efc23.appspot.com',
    iosClientId: '604985196280-8ne98kgktii53dk733ug65g69krtqcn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearning',
  );
}
